CREATE TABLE `tb_hello_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bigDecimalFlag` decimal(19,2) NOT NULL,
  `bool_obj_flag` bit(1) NOT NULL,
  `byte_flag` tinyint(4) DEFAULT NULL,
  `char_flag` char(1) DEFAULT NULL,
  `char_obj_flag` char(1) DEFAULT NULL,
  `date_flag` date DEFAULT NULL,
  `double_fg` double NOT NULL,
  `double_obj_flag` double DEFAULT NULL,
  `_float_flag` float NOT NULL,
  `float_obj_flag` float DEFAULT NULL,
  `int_flag` int(11) NOT NULL,
  `integer_obj_flag` int(11) NOT NULL,
  `last_login_date` datetime NOT NULL,
  `long_flag` bigint(20) DEFAULT NULL,
  `long_obj_flag` bigint(20) DEFAULT NULL,
  `on_line` bit(1) NOT NULL,
  `role_gender_flag` int(11) DEFAULT NULL,
  `short_flag` smallint(6) DEFAULT NULL,
  `short_obj_flag` smallint(6) NOT NULL,
  `string_flag` varchar(255) DEFAULT NULL,
  `time_flag` time DEFAULT NULL,
  `user_gender_flag` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8